# Generated by Django 4.1.5 on 2023-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('specifications', models.TextField(max_length=500, verbose_name='specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('quantity_product_in_shop', models.PositiveIntegerField(default=1, null=True, verbose_name='quantity products')),
                ('shop', models.ManyToManyField(null=True, to='products.shopforproduct', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
